export interface Project {
  id: string;
  title: string;
  context: string;
  role: string;
  period: string;
  metricBadge: string;
  problem: string;
  whatIBuilt: string;
  whatItTookToShip: string;
  tags: string[];
  repoUrl?: string;
  isPaperUnderReview?: boolean;
}

export const projects: Project[] = [
  {
    id: "cstr-parameter-identification",
    title: "Parameter Identification of a Nonlinear CSTR",
    context: "Final-year major project with MLAPC Lab, MIT Manipal",
    role: "Co-author & Lead Estimator",
    period: "Feb 2026 – Present",
    metricBadge: "R² ≥ 0.9976 · 12.3× lower RMSE",
    problem:
      "Pilot-plant continuous stirred-tank reactors exhibit acute nonlinear kinetic and thermal coupling that standard linear estimators fail to track, risking thermal runaway and degraded conversion during unmodelled parameter drift.",
    whatIBuilt:
      "A Constrained-Gain Unscented Kalman Filter in Python identifying 7 kinetic and heat-transfer parameters of a 1 L double-jacketed pilot-plant CSTR, formulated as an 11-state augmented estimation problem with RK4 integration and 27 sigma points per sample. One fixed filter configuration validated across three excitation datasets (ramp–staircase, PRBS, RBS; 3,133–4,781 samples), reproducing reactor temperature at R² ≥ 0.9976 with RMSE 0.10–0.33 °C, zero constraint violations, and 12.3× lower RMSE than the lab's particle-swarm-optimisation benchmark. Co-author on a journal paper submitted from this work.",
    whatItTookToShip:
      "Formulated state augmentations to eliminate numerical instability under stiff reaction kinetics; enforced physical parameter bounds directly in the gain computation loop without compromising real-time execution; structured rigorous multi-dataset validation protocols and co-authored the formal manuscript currently under peer review.",
    tags: ["Python", "NumPy", "SciPy", "Kalman filtering", "system identification"],
    isPaperUnderReview: true,
  },
  {
    id: "clauseguard",
    title: "ClauseGuard — AI Contract Red-Flag Detector",
    context: "Open-source legal-tech product",
    role: "Sole Architect & Full-Stack Developer",
    period: "2025 – 2026",
    metricBadge: "0.869 Avg F1 · 510 CUAD Contracts",
    problem:
      "Enterprise legal teams waste dozens of hours manually scanning counterparty agreements for hidden liabilities, uncapped indemnity clauses, and non-standard termination terms buried inside dense legal boilerplate.",
    whatIBuilt:
      "End-to-end ML pipeline over the 510-contract CUAD dataset: 34 annotation categories consolidated into 7 risk groups, negatives generated by cross-group sampling, clauses deduplicated, 80/10/10 split. Seven binary logistic-regression classifiers on a shared 10,000-feature TF-IDF representation (unigrams + bigrams) with balanced class weights, reaching 0.869 average F1 on the held-out test set (0.784–0.911 across risk groups). Shipped as a full product: FastAPI backend with 8 REST endpoints, JWT + bcrypt auth, SQLAlchemy/SQLite persistence, PDF/DOCX extraction via PyMuPDF and python-docx, regex clause chunking, and a JS single-page frontend showing per-clause risk levels and an aggregate contract risk score.",
    whatItTookToShip:
      "Engineered the hierarchical taxonomy reducing 34 fragmented annotations into 7 high-impact risk categories; built deterministic regex boundary chunking to handle broken PDF text layers without dropping clauses; kept inference round-trip under 450ms per multi-page document while persisting authenticated user sessions and audit-ready risk breakdowns.",
    tags: ["Python", "scikit-learn", "FastAPI", "JWT", "SQLAlchemy"],
    repoUrl: "https://github.com/Anshika-17a/contract-red-flag-detector",
  },
  {
    id: "cybershield-ai",
    title: "CyberShield AI — Phishing & Threat Detection Platform",
    context: "Open-source security intelligence",
    role: "Full-Stack ML Engineer",
    period: "2025 – 2026",
    metricBadge: "500k+ URLs · Multi-lingual AI",
    problem:
      "Generic threat models rely on outdated global blocklists that miss short-lived zero-day phishing links and fail completely against localized Indian fraud vectors targeting UPI payments, electricity bills, and fake KYC updates.",
    whatIBuilt:
      "LinearSVC classifiers for malicious-URL and scam-SMS detection trained on a 500,000+ URL corpus, combining TF-IDF features with entropy analysis and keyword heuristics. False positives cut by adding a whitelist trust layer over 50+ Indian banking and commerce domains, and the SMS model tuned on Indian scam patterns (UPI, KYC, electricity-bill fraud) that global spam datasets miss. Built as a React/Vite + Flask platform with Tesseract OCR screenshot scanning, a multilingual Gemini chatbot (Hindi, Tamil, Telugu), auto-generated forensic PDF reports and a live latency/confidence dashboard.",
    whatItTookToShip:
      "Tuned custom character-entropy and lexical ratio extractors to flag disguised punycode domains; architected a dual-stage trust evaluation engine preventing false flags on genuine Indian financial portals; integrated Google Gemini API with strict structured schema validation to generate real-time forensic reports and localized user guidance.",
    tags: ["Python", "scikit-learn", "Flask", "React", "Gemini API"],
    repoUrl: "https://github.com/Anshika-17a/CyberShield_AI",
  },
  {
    id: "rfid-surgical-sponge-tracker",
    title: "RFID-Based Surgical Sponge Tracking System",
    context: "Government-Funded Hardware Prototype · Karnataka NAIN 2.0",
    role: "Team Lead (6 Members)",
    period: "2025 – Present",
    metricBadge: "₹5,00,000 Grant · 6-Member Team",
    problem:
      "Retained surgical items (RSIs), predominantly surgical gauze sponges left inside abdominal cavities, lead to severe septic complications, emergency re-operations, and heavy malpractice claims. Manual sponge counting under intraoperative stress suffers documented failure rates.",
    whatIBuilt:
      "A medical hardware-software tracking device that monitors surgical sponges throughout operative procedures and immediately alerts surgical staff if any item remains unaccounted for before wound closure. Prototyping tag-and-reader detection stages using high-permeability biocompatible RFID tags, antenna array calibration, and diagnostic telemetry designed for saline- and fluid-saturated clinical operating environments.",
    whatItTookToShip:
      "Pitched and secured ₹5,00,000 non-dilutive government innovation funding under Karnataka NAIN 2.0; authored the complete engineering product requirements document (PRD); led sprint planning, subsystem decomposition, and onboarding across 5 cross-functional peers spanning embedded firmware, hardware circuit design, and software telemetry; running milestone reviews with medical domain advisors ahead of bench validation.",
    tags: ["RFID", "embedded systems", "requirements engineering", "sprint planning"],
  },
];
