export interface Project {
  slug: string;
  title: string;
  role: string;
  period: string;
  problem: string;
  built: string;
  shipped: string;
  tags: string[];
  repoUrl?: string;
  featured: boolean;
  context?: string;
  metricBadge?: string;
  isPaperUnderReview?: boolean;
  summary?: string;
  builtLabel?: string;
  shippedLabel?: string;
  statusBadge?: string;
}

export const projects: Project[] = [
  {
    slug: "cstr-parameter-identification",
    title: "Parameter Identification of a Nonlinear CSTR",
    context: "Final-year major project with MLAPC Lab, MIT Manipal",
    role: "Co-author & Lead Estimator",
    period: "Feb 2026 – Present",
    metricBadge: "R² ≥ 0.9976 · 12.3× lower RMSE",
    statusBadge: "Active Research · In Progress",
    builtLabel: "What I'm Building",
    shippedLabel: "What It Takes To Ship",
    problem:
      "Pilot-plant continuous stirred-tank reactors exhibit acute nonlinear kinetic and thermal coupling that standard linear estimators fail to track, risking thermal runaway and degraded conversion during unmodelled parameter drift.",
    built:
      "A Constrained-Gain Unscented Kalman Filter in Python identifying 7 kinetic and heat-transfer parameters of a 1 L double-jacketed pilot-plant CSTR, formulated as an 11-state augmented estimation problem with RK4 integration and 27 sigma points per sample. One fixed filter configuration validated across three excitation datasets (ramp–staircase, PRBS, RBS; 3,133–4,781 samples), reproducing reactor temperature at R² ≥ 0.9976 with RMSE 0.10–0.33 °C, zero constraint violations, and 12.3× lower RMSE than the lab's particle-swarm-optimisation benchmark. Co-author on a journal paper submitted from this work.",
    shipped:
      "Formulated state augmentations to eliminate numerical instability under stiff reaction kinetics; enforced physical parameter bounds directly in the gain computation loop without compromising real-time execution; structured rigorous multi-dataset validation protocols and co-authored the formal manuscript currently under peer review.",
    tags: ["Python", "NumPy", "SciPy", "Kalman filtering", "system identification"],
    isPaperUnderReview: true,
    featured: true,
  },
  {
    slug: "clauseguard",
    title: "ClauseGuard — AI Contract Red-Flag Detector",
    context: "Open-source legal-tech product",
    role: "Sole Architect & Full-Stack Developer",
    period: "2025 – 2026",
    metricBadge: "0.869 Avg F1 · 510 CUAD Contracts",
    problem:
      "Enterprise legal teams waste dozens of hours manually scanning counterparty agreements for hidden liabilities, uncapped indemnity clauses, and non-standard termination terms buried inside dense legal boilerplate.",
    built:
      "End-to-end ML pipeline over the 510-contract CUAD dataset: 34 annotation categories consolidated into 7 risk groups, negatives generated by cross-group sampling, clauses deduplicated, 80/10/10 split. Seven binary logistic-regression classifiers on a shared 10,000-feature TF-IDF representation (unigrams + bigrams) with balanced class weights, reaching 0.869 average F1 on the held-out test set (0.784–0.911 across risk groups). Shipped as a full product: FastAPI backend with 8 REST endpoints, JWT + bcrypt auth, SQLAlchemy/SQLite persistence, PDF/DOCX extraction via PyMuPDF and python-docx, regex clause chunking, and a JS single-page frontend showing per-clause risk levels and an aggregate contract risk score.",
    shipped:
      "Engineered the hierarchical taxonomy reducing 34 fragmented annotations into 7 high-impact risk categories; built deterministic regex boundary chunking to handle broken PDF text layers without dropping clauses; kept inference round-trip under 450ms per multi-page document while persisting authenticated user sessions and audit-ready risk breakdowns.",
    tags: ["Python", "scikit-learn", "FastAPI", "JWT", "SQLAlchemy"],
    repoUrl: "https://github.com/Anshika-17a/contract-red-flag-detector",
    featured: true,
  },
  {
    slug: "loan-risk-scoring",
    title: "Loan Default Risk Scoring & Explanation Service",
    role: "Solo build",
    period: "2026",
    repoUrl: "https://github.com/Anshika-17a/Loan",
    tags: ["Python", "XGBoost", "FastAPI", "PostgreSQL", "SHAP", "Docker"],
    problem:
      "A lender that declines an application has to be able to say why. A credit model that cannot explain its own output is not deployable, however accurate it is. So the task is two things at once: score the risk, and justify the score in terms a human can act on.",
    built:
      "An XGBoost classifier over applicant financial and bureau features: income, credit and annuity amounts, employment and age history, education level, external bureau scores and regional indicators. Median imputation, one-hot encoding for categoricals, stratified 80/20 split. Class imbalance handled with a computed scale_pos_weight rather than resampling, so the minority default class isn't drowned out and the training distribution stays honest. Tuned at 300 estimators, 0.05 learning rate, depth 5, evaluated on ROC-AUC with a full confusion matrix; every run writes its model, feature list and evaluation report to disk as versioned artifacts.",
    shipped:
      "Built as a service rather than a notebook: a FastAPI backend over PostgreSQL with automated feature engineering on customer registration, a low-latency scoring endpoint, SHAP values returned alongside every prediction so a decision can be explained feature by feature, and an audit trail of key actions. Containerised with Docker and docker-compose for reproducible setup, with seed and verification scripts covering registration, login, risk logic and the full end-to-end flow. Schema holds no PII or credentials.",
    featured: true,
  },
  {
    slug: "cybershield-ai",
    title: "CyberShield AI — Phishing & Threat Detection Platform",
    context: "Open-source security intelligence",
    role: "Full-Stack ML Engineer",
    period: "2025 – 2026",
    metricBadge: "500k+ URLs · Multi-lingual AI",
    problem:
      "Generic threat models rely on outdated global blocklists that miss short-lived zero-day phishing links and fail completely against localized Indian fraud vectors targeting UPI payments, electricity bills, and fake KYC updates.",
    built:
      "LinearSVC classifiers for malicious-URL and scam-SMS detection trained on a 500,000+ URL corpus, combining TF-IDF features with entropy analysis and keyword heuristics. False positives cut by adding a whitelist trust layer over 50+ Indian banking and commerce domains, and the SMS model tuned on Indian scam patterns (UPI, KYC, electricity-bill fraud) that global spam datasets miss. Built as a React/Vite + Flask platform with Tesseract OCR screenshot scanning, a multilingual Gemini chatbot (Hindi, Tamil, Telugu), auto-generated forensic PDF reports and a live latency/confidence dashboard.",
    shipped:
      "Tuned custom character-entropy and lexical ratio extractors to flag disguised punycode domains; architected a dual-stage trust evaluation engine preventing false flags on genuine Indian financial portals; integrated Google Gemini API with strict structured schema validation to generate real-time forensic reports and localized user guidance.",
    tags: ["Python", "scikit-learn", "Flask", "React", "Gemini API"],
    repoUrl: "https://github.com/Anshika-17a/CyberShield_AI",
    featured: true,
  },
  {
    slug: "rfid-surgical-sponge-tracker",
    title: "RFID-Based Surgical Sponge Tracking System",
    context: "Government-Funded Hardware Prototype · Karnataka NAIN 2.0",
    role: "Team Lead (6 Members)",
    period: "2025 – Present",
    metricBadge: "₹5,00,000 Grant · 6-Member Team",
    statusBadge: "Under Production",
    builtLabel: "What We're Building",
    shippedLabel: "What It Takes To Ship",
    problem:
      "Retained surgical items (RSIs), predominantly surgical gauze sponges left inside abdominal cavities, lead to severe septic complications, emergency re-operations, and heavy malpractice claims. Manual sponge counting under intraoperative stress suffers documented failure rates.",
    built:
      "A medical hardware-software tracking device that monitors surgical sponges throughout operative procedures and immediately alerts surgical staff if any item remains unaccounted for before wound closure. Prototyping tag-and-reader detection stages using high-permeability biocompatible RFID tags, antenna array calibration, and diagnostic telemetry designed for saline- and fluid-saturated clinical operating environments.",
    shipped:
      "Pitched and secured ₹5,00,000 non-dilutive government innovation funding under Karnataka NAIN 2.0; authored the complete engineering product requirements document (PRD); led sprint planning, subsystem decomposition, and onboarding across 5 cross-functional peers spanning embedded firmware, hardware circuit design, and software telemetry; running milestone reviews with medical domain advisors ahead of bench validation.",
    tags: ["RFID", "Embedded Systems", "Hardware Architecture", "NAIN 2.0"],
    featured: true,
  },
  {
    slug: "gemma-multimodal-assistant",
    title: "Applied Generative AI Solution (Gemma)",
    role: "Hackathon Winner",
    period: "2026",
    problem: "Real-world utility and inference efficiency challenges during high-stress 24-hour prototype build sprints.",
    built: "Applied generative AI architecture utilizing Google Gemma with optimized inference quantization and structured prompting.",
    shipped: "Built and deployed under a 24-hour sprint; awarded Winner at Google Build with Gemma Hackathon (Kaggle).",
    tags: ["Google Gemma", "GenAI", "Kaggle", "PyTorch"],
    featured: false,
    summary: "Hackathon-winning applied generative AI solution built and deployed using Google Gemma under a 24-hour Kaggle sprint.",
  },
  {
    slug: "reality-rewritten-verification",
    title: "Frontline Verification Intelligence Prototype",
    role: "Hackathon Winner",
    period: "2025",
    problem: "Manual verification bottlenecks in high-frequency document and credential inspection workflows.",
    built: "Applied AI product providing automated inspection, extraction, and forensic integrity validation.",
    shipped: "Delivered full working prototype and live demo to the jury, winning 1st place at Reality Rewritten National Hackathon.",
    tags: ["Computer Vision", "FastAPI", "React", "Python"],
    featured: false,
    summary: "National hackathon winner delivering full-stack automated verification intelligence under live jury evaluation.",
  },
];
